# Generated by Django 5.0.1 on 2024-03-24 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EXEplorer', '0006_userprofile_next_pet_appearance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='datetime',
            field=models.CharField(default='new', max_length=100),
        ),
    ]
